// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeLc2GIinYT6yGzuk3bzXCddIouPgS3ro',
    appId: '1:685909948501:web:fcda9c5683d913ec3dbcdc',
    messagingSenderId: '685909948501',
    projectId: 'enlace-original',
    authDomain: 'enlace-original.firebaseapp.com',
    storageBucket: 'enlace-original.appspot.com',
    measurementId: 'G-R10JCHJNLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACXeBFD34FlGmfQyFPssgUbddrtncBpsI',
    appId: '1:685909948501:android:ead6496796f13ebd3dbcdc',
    messagingSenderId: '685909948501',
    projectId: 'enlace-original',
    storageBucket: 'enlace-original.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDET8JmPpovQnu2ItRx2ehIMVWi7GmsW0U',
    appId: '1:685909948501:ios:0806b551314c4bc33dbcdc',
    messagingSenderId: '685909948501',
    projectId: 'enlace-original',
    storageBucket: 'enlace-original.appspot.com',
    iosBundleId: 'com.example.enlace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDET8JmPpovQnu2ItRx2ehIMVWi7GmsW0U',
    appId: '1:685909948501:ios:0806b551314c4bc33dbcdc',
    messagingSenderId: '685909948501',
    projectId: 'enlace-original',
    storageBucket: 'enlace-original.appspot.com',
    iosBundleId: 'com.example.enlace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeLc2GIinYT6yGzuk3bzXCddIouPgS3ro',
    appId: '1:685909948501:web:14393a022a3e79183dbcdc',
    messagingSenderId: '685909948501',
    projectId: 'enlace-original',
    authDomain: 'enlace-original.firebaseapp.com',
    storageBucket: 'enlace-original.appspot.com',
    measurementId: 'G-VKRF7M9FWQ',
  );
}
